// Have indicators of literal meaning and intended meaning and indicators to differentiate similarities


window['Chinese'] = {
    'Pinyin & Zhuyin': [
      { zhuying: 'ㄅ', pinyin: 'b', audio: 'ㄅ.(🎵)', },
      { zhuying: 'ㄆ', pinyin: 'p', audio: 'ㄆ.(🎵)', },
      { zhuying: 'ㄇ', pinyin: 'm', audio: 'ㄇ.(🎵)', },
      { zhuying: 'ㄈ', pinyin: 'f', audio: 'ㄈ.(🎵)', },
      { zhuying: 'ㄉ', pinyin: 'd', audio: 'ㄉ.(🎵)', },
      { zhuying: 'ㄊ', pinyin: 't', audio: 'ㄊ.(🎵)', },
      { zhuying: 'ㄋ', pinyin: 'n', audio: 'ㄋ.(🎵)', },
      { zhuying: 'ㄌ', pinyin: 'l', audio: 'ㄌ.(🎵)', },
      { zhuying: 'ㄍ', pinyin: 'g', audio: 'ㄍ.(🎵)', },
      { zhuying: 'ㄎ', pinyin: 'k', audio: 'ㄎ.(🎵)', },
      { zhuying: 'ㄏ', pinyin: 'h', audio: 'ㄏ.(🎵)', },
      { zhuying: 'ㄐ', pinyin: 'j', audio: 'ㄐ.(🎵)', },
      { zhuying: 'ㄑ', pinyin: 'q', audio: 'ㄑ.(🎵)', },
      { zhuying: 'ㄒ', pinyin: 'x', audio: 'ㄒ.(🎵)', },
      { zhuying: 'ㄓ', pinyin: 'zh', audio: 'ㄓ.(🎵)', },
      { zhuying: 'ㄔ', pinyin: 'ch', audio: 'ㄔ.(🎵)', },
      { zhuying: 'ㄕ', pinyin: 'sh', audio: 'ㄕ.(🎵)', },
      { zhuying: 'ㄖ', pinyin: 'r', audio: 'ㄖ.(🎵)', },
      { zhuying: 'ㄗ', pinyin: 'z', audio: 'ㄗ.(🎵)', },
      { zhuying: 'ㄘ', pinyin: 'c', audio: 'ㄘ.(🎵)', },
      { zhuying: 'ㄙ', pinyin: 's', audio: 'ㄙ.(🎵)', },
      { zhuying: 'ㄚ', pinyin: 'a', audio: 'ㄚ.(🎵)', },
      { zhuying: 'ㄛ', pinyin: 'o', audio: 'ㄛ.(🎵)', },
      { zhuying: 'ㄜ', pinyin: 'e', audio: 'ㄜ.(🎵)', },
      { zhuying: 'ㄝ', pinyin: 'ê', audio: 'ㄝ.(🎵)', },
      { zhuying: 'ㄞ', pinyin: 'ai', audio: 'ㄞ.(🎵)', },
      { zhuying: 'ㄟ', pinyin: 'ei', audio: 'ㄟ.(🎵)', },
      { zhuying: 'ㄠ', pinyin: 'ao', audio: 'ㄠ.(🎵)', },
      { zhuying: 'ㄡ', pinyin: 'ou', audio: 'ㄡ.(🎵)', },
      { zhuying: 'ㄢ', pinyin: 'an', audio: 'ㄢ.(🎵)', },
      { zhuying: 'ㄣ', pinyin: 'en', audio: 'ㄣ.(🎵)', },
      { zhuying: 'ㄤ', pinyin: 'ang', audio: 'ㄤ.(🎵)', },
      { zhuying: 'ㄥ', pinyin: 'eng', audio: 'ㄥ.(🎵)', },
      { zhuying: 'ㄦ', pinyin: 'er', audio: 'ㄦ.(🎵)', },
      { zhuying: 'ㄧ', pinyin: 'i', audio: 'ㄧ.(🎵)', },
      { zhuying: 'ㄧㄚ', pinyin: 'ia', audio: 'ㄧㄚ.(🎵)', },
      { zhuying: 'ㄧㄛ', pinyin: 'io', audio: 'ㄧㄛ.(🎵)', },
      { zhuying: 'ㄧㄝ', pinyin: 'iê', audio: 'ㄧㄝ.(🎵)', },
      { zhuying: 'ㄧㄞ', pinyin: 'iai', audio: 'ㄧㄞ.(🎵)', },
      { zhuying: 'ㄧㄠ', pinyin: 'iao', audio: 'ㄧㄠ.(🎵)', },
      { zhuying: 'ㄧㄡ', pinyin: 'iu', audio: 'ㄧㄡ.(🎵)', },
      { zhuying: 'ㄧㄢ', pinyin: 'ian', audio: 'ㄧㄢ.(🎵)', },
      { zhuying: 'ㄧㄣ', pinyin: 'in', audio: 'ㄧㄣ.(🎵)', },
      { zhuying: 'ㄧㄤ', pinyin: 'iang', audio: 'ㄧㄤ.(🎵)', },
      { zhuying: 'ㄧㄥ', pinyin: 'ing', audio: 'ㄧㄥ.(🎵)', },
      { zhuying: 'ㄨ', pinyin: 'u', audio: 'ㄨ.(🎵)', },
      { zhuying: 'ㄨㄚ', pinyin: 'ua', audio: 'ㄨㄚ.(🎵)', },
      { zhuying: 'ㄨㄛ', pinyin: 'uo', audio: 'ㄨㄛ.(🎵)', },
      { zhuying: 'ㄨㄞ', pinyin: 'uai', audio: 'ㄨㄞ.(🎵)', },
      { zhuying: 'ㄨㄟ', pinyin: 'ui', audio: 'ㄨㄟ.(🎵)', },
      { zhuying: 'ㄨㄢ', pinyin: 'uan', audio: 'ㄨㄢ.(🎵)', },
      { zhuying: 'ㄨㄣ', pinyin: 'uen', audio: 'ㄨㄣ.(🎵)', },
      { zhuying: 'ㄨㄤ', pinyin: 'uang', audio: 'ㄨㄤ.(🎵)', },
      { zhuying: 'ㄨㄥ', pinyin: 'ong', audio: 'ㄨㄥ.(🎵)', },
      { zhuying: 'ㄩ', pinyin: 'ü', audio: 'ㄩ.(🎵)', },
      { zhuying: 'ㄩㄝ', pinyin: 'üê', audio: 'ㄩㄝ.(🎵)', },
      { zhuying: 'ㄩㄢ', pinyin: 'üan', audio: 'ㄩㄢ.(🎵)', },
      { zhuying: 'ㄩㄣ', pinyin: 'ün', audio: 'ㄩㄣ.(🎵)', },
      { zhuying: 'ㄩㄥ', pinyin: 'iong', audio: 'ㄩㄥ.(🎵)', },
    ],
    'Number': [
      { cn: '零', pinyin: 'líng', en: 'zero', audio: '零.(🎵)', }, 
      { cn: '一', pinyin: 'yī', en: 'one', audio: '一.(🎵)', }, 
      { cn: '二', pinyin: 'èr', en: 'two', audio: '二.(🎵)', }, 
      { cn: '三', pinyin: 'sān', en: 'three', audio: '三.(🎵)', },
      { cn: '四', pinyin: 'sì', en: 'four', audio: '四.(🎵)', },
      { cn: '五', pinyin: 'wǔ', en: 'five', audio: '五.(🎵)', },
      { cn: '六', pinyin: 'liù', en: 'six', audio: '六.(🎵)', },
      { cn: '七', pinyin: 'qī', en: 'seven', audio: '七.(🎵)', },
      { cn: '八', pinyin: 'bā', en: 'eight', audio: '八.(🎵)', },
      { cn: '九', pinyin: 'jiǔ', en: 'nine', audio: '九.(🎵)', },
      { cn: '十', pinyin: 'shí', en: 'ten', audio: '十.(🎵)', },
      { cn: '百', pinyin: 'bǎi', en: 'hundred', audio: '百.(🎵)', },
      { cn: '千', pinyin: 'qiān', en: 'thousand', audio: '千.(🎵)', },
      { cn: '万', pinyin: 'wàn', en: 'ten thousand', audio: '万.(🎵)', },
      { cn: '亿', pinyin: 'yì', en: 'hundred million', audio: '亿.(🎵)', },
    ],
    // Test to make sure there isn't any duplicate answers
    'Pronouns': [
      { cn: '我', pinyin: 'wǒ', en: 'me, I', audio: '我.(🎵)', },
      { cn: '你', pinyin: 'nǐ', en: 'you', audio: '你.(🎵)', }, 
      { cn: '您', pinyin: 'nín', en: 'you (polite)', audio: '您.(🎵)', }, 
      { cn: '他', pinyin: 'tā', en: 'he/him', audio: '他，她.(🎵)', }, 
      { cn: '她', pinyin: 'tā', en: 'she', audio: '他，她.(🎵)', }, 
      { cn: '我们', pinyin: 'wǒ men', en: 'us', audio: '我们.(🎵)', }, 
      { cn: '你们', pinyin: 'nǐ men', en: 'you (plural)', audio: '你们.(🎵)', }, 
      { cn: '您们', pinyin: 'nín men', en: 'you (polite, plural)', audio: '您们.(🎵)', }, 
      { cn: '他们', pinyin: 'tā men', en: 'them (male)', audio: '他们，她们.(🎵)', }, 
      { cn: '她们', pinyin: 'tā men', en: 'them', audio: '他们，她们.(🎵)', }, 
      { cn: '我的', pinyin: 'wǒ de', en: 'mine', audio: '我的.(🎵)', }, 
      { cn: '你的', pinyin: 'nǐ de', en: 'yours', audio: '你的.(🎵)', }, 
      { cn: '您的', pinyin: 'nín de', en: 'yours (polite)', audio: '您的.(🎵)', }, 
      { cn: '他的', pinyin: 'tā de', en: 'his', audio: '他的，她的.(🎵)', }, 
      { cn: '她的', pinyin: 'tā de', en: 'her/hers', audio: '他的，她的.(🎵)', }, /* 2 */
      { cn: '我们的', pinyin: 'wǒ men de', en: 'ours', audio: '我们的.(🎵)', }, 
      { cn: '你们的', pinyin: 'nǐ men de', en: 'yours (plural) ', audio: '你们的.(🎵)', }, 
      { cn: '您们的', pinyin: 'nín men de', en: 'yours (polite plural)', audio: '您们的.(🎵)', }, 
      { cn: '他们的', pinyin: 'tā men de', en: 'theirs (male or both)', audio: '他们的，她们的.(🎵)', }, /* 1 */ 
      { cn: '她们的',  pinyin: 'tā men de', en: 'theirs (female)', audio: '他们的，她们的.(🎵)', }, 
    ]
    ,
    'Family': [

      { cn: '兄弟姊妹', pinyin: 'xiōng dì zǐ mèi', en: 'siblings', audio: '兄弟姊妹.(🎵)', },
      { cn: '亲戚', pinyin: 'qīn qi', en: 'relative', audio: '亲戚.(🎵)', },
      { cn: '家庭', pinyin: 'jiā tíng', en: 'family / household', audio: '家庭.(🎵)', }, 
      { cn: '父母', pinyin: 'fù mǔ', en: 'father and mother / parents', audio: '父母.(🎵)', }, 
      { cn: '配偶', pinyin: 'pèi ǒu', en: 'spouse', audio: '配偶.(🎵)', }, 

      { cn: '爸爸', pinyin: 'bà ba', en: 'dad', audio: '爸爸.(🎵)', }, 
      { cn: '父亲', pinyin: 'fù qīn', en: 'father', audio: '父亲.(🎵)', }, /* 1 */
      { cn: '妈妈', pinyin: 'mā mā', en: 'mom', audio: '妈妈.(🎵)', }, 
      { cn: '母亲', pinyin: 'mǔ qīn', en: 'mother', audio: '母亲.(🎵)', },  /* 1 */
      { cn: '继母', pinyin: 'jì mǔ', en: 'step mother', audio: '继母.(🎵)', }, 
      { cn: '哥哥', pinyin: 'gē ge', en: 'older brother', audio: '哥哥.(🎵)', }, 
      { cn: '弟弟', pinyin: 'dì di', en: 'younger brother', audio: '弟弟.(🎵)', }, 
      { cn: '姐姐', pinyin: 'jiě jie', en: 'older sister', audio: '姐姐.(🎵)', }, 
      { cn: '妹妹', pinyin: 'mèi mèi', en: 'younger sister', audio: '妹妹.(🎵)', },
  
      { cn: '先生', pinyin: 'xiān sheng', en: 'mister', audio: '先生.(🎵)', }, 
      { cn: '丈夫', pinyin: 'zhàng fu', en: 'husband (formal)', audio: '丈夫.(🎵)', }, 
      { cn: '老公', pinyin: 'lǎo gong', en: 'husband (informal)', audio: '老公.(🎵)', }, 
      { cn: '太太', pinyin: 'tài tai', en: 'missus', audio: '太太.(🎵)', }, 
      { cn: '夫人', pinyin: 'fū rén', en: 'missus (old chinese)', audio: '夫人.(🎵)', }, 
      { cn: '妻子', pinyin: 'qī zi', en: 'wife (formal)', audio: '妻子.(🎵)', },
      { cn: '老婆', pinyin: 'lǎo pó', en: 'wife (informal)', audio: '老婆.(🎵)', },
  
      { cn: '孩子', pinyin: 'hái zi', en: 'child', audio: '孩子.(🎵)', }, 
      { cn: '儿子', pinyin: 'ér zi', en: 'son', audio: '儿子.(🎵)', }, 
      { cn: '女儿', pinyin: 'nǚ ér', en: 'daughter', audio: '女儿.(🎵)', }, 
      { cn: '孙女', pinyin: 'sūn nǚ', en: 'granddaughter', audio: '孙女.(🎵)', }, // Check for distinction between father's and mother's side
      { cn: '孙子', pinyin: 'sūn zi', en: 'grandson', audio: '孙子.(🎵)', }, // Check for distincition between father's and mother's side

      { cn: '爷爷', pinyin: 'yé ye', en: 'grandpa (dad\'s side)', audio: '爷爷.(🎵)', }, 
      { cn: '奶奶', pinyin: 'nǎi nai', en: 'grandma (dad\'s side)', audio: '奶奶.(🎵)', },
      { cn: '公公', pinyin: 'gōng gōng', en: 'grandpa (north chinese)  (mom\'s Side)', audio: '公公.(🎵)', },
      { cn: '姥姥', pinyin: 'lǎo lǎo', en: 'grandma (north chinese) (mom\'s Side)', audio: '姥姥.(🎵)', },
      { cn: '外公', pinyin: 'wài gōng', en: 'grandpa (south Chinese) (mom\'s Side)', audio: '外公.(🎵)', },
      { cn: '外婆', pinyin: 'wài pó', en: 'grandma (south Chinese) (mom\'s Side)', audio: '外婆.(🎵)', }, 
      { cn: '祖父', pinyin: 'zǔ fù', en: 'grandfather (dad\'s side)', audio: '祖父.(🎵)', }, 
      { cn: '祖母', pinyin: 'zǔ mǔ', en: 'grandmother (dad\'s side)', audio: '祖母.(🎵)', },
      { cn: '外祖父', pinyin: 'wài zǔ fù', en: 'grandfather (mom\'s side)', audio: '外祖父.(🎵)', }, 
      { cn: '外祖母', pinyin: 'wài zǔ mǔ', en: 'grandmother (mom\'s side)', audio: '外祖母.(🎵)', },
      { cn: '岳父', pinyin: 'yuè fù', en: 'father-in-law', audio: '岳父.(🎵)', },
      { cn: '岳母', pinyin: 'yuè mǔ', en: 'mother-in-law', audio: '岳母.(🎵)', },

      { cn: '叔叔', pinyin: 'shū shu', en: 'uncle (dad\'s younger brother)', audio: '叔叔.(🎵)', },
      { cn: '姑夫', pinyin: 'gū fū', en: 'uncle (dad\'s younger sister\'s husband)', audio: '姑夫.(🎵)', },
      { cn: '舅舅', pinyin: 'jiù jiu', en: 'uncle (mother\'s brother)', audio: '舅舅.(🎵)', },
      { cn: '伯伯', pinyin: 'bó bo', en: 'uncle (dad\'s older brother)', audio: '伯伯.(🎵)', },
      { cn: '姨丈', pinyin: 'yí zhàng', en: 'uncle (mother\'s sister\'s husband)', audio: '姨丈.(🎵)', },
      { cn: '姑丈', pinyin: 'gū zhàng', en: 'uncle (dad\'s older sister\'s husband) ', audio: '姑丈.(🎵)', },

      { cn: '阿姨', pinyin: 'Ā yí', en: 'aunt (mom\'s younger sister)', audio: '阿姨.(🎵)', },
      { cn: '婶婶', pinyin: 'shěn shen', en: 'aunt (dad\'s younger brother\'s wife)', audio: '婶婶.(🎵)', },
      { cn: '伯母', pinyin: 'bó mǔ', en: 'aunt (dad\'s older brother\'s wife)', audio: '伯母.(🎵)', },
      { cn: '舅母', pinyin: 'jiù mu', en: 'aunt (mom\'s brother\'s wife)', audio: '舅母.(🎵)', }, // (no old or young)
      { cn: '姑姑', pinyin: 'gū gu', en: 'aunt (dad\'s younger sister)', audio: '姑姑.(🎵)', },
      { cn: '姑妈', pinyin: 'gū mā', en: 'aunt (dad\'s older sister)', audio: '姑妈.(🎵)', },
      { cn: '姨妈', pinyin: 'yí mā', en: 'aunt (mom\'s older sister)', audio: '姨妈.(🎵)', },

      { cn: '表哥', pinyin: 'biǎo gē', en: 'cousin (older than you) (male) (different family name from you)', audio: '表哥.(🎵)', },
      { cn: '表弟', pinyin: 'biǎo dì', en: 'cousin (younger than you) (male) (different family name from you)', audio: '表弟.(🎵)', },
      { cn: '表妹', pinyin: 'biǎo mèi', en: 'cousin (younger than you) (female) (different family name from you)', audio: '表妹.(🎵)', },
      { cn: '表姐', pinyin: 'biǎo jiě', en: 'cousin (older than you) (female) (different family name from you)', audio: '表姐.(🎵)', },
      { cn: '堂兄', pinyin: 'táng xiōng', en: 'cousin (older than you) (male) (same family name as you)', audio: '堂兄.(🎵)', },
      { cn: '堂弟', pinyin: 'táng dì', en: 'cousin (younger than you) (male) (same family name as you)', audio: '堂弟.(🎵)', },
      { cn: '堂姐', pinyin: 'táng jiě', en: 'cousin (older than you) (female) (same family name as you)', audio: '堂姐.(🎵)', },
      { cn: '堂妹', pinyin: 'táng mèi', en: 'cousin (younger than you) (female) (same family name as you)', audio: '堂妹.(🎵)', },

      { cn: '姐夫', pinyin: 'jiě fū', en: 'brother-in-law (older sister side)', audio: '姐夫.(🎵)', },
      { cn: '嫂子', pinyin: 'sǎo zi', en: 'sister-in-law (older brother side)', audio: '嫂子.(🎵)', },
      { cn: '妹夫', pinyin: 'mèi fū', en: 'brother-in-law (younger sister side)', audio: '妹夫.(🎵)', },
      { cn: '弟妹', pinyin: 'dì mèi', en: 'sister-in-law (younger brother side)', audio: '弟妹.(🎵)', },
      { cn: '女婿', pinyin: 'nǚ xù', en: 'son-in-law', audio: '女婿.(🎵)', },
      { cn: '儿媳', pinyin: 'ér xí', en: 'daughter-in-law', audio: '儿媳.(🎵)', },

      { cn: '侄子', pinyin: 'zhí zi', en: 'nephew (brother\'s side)', audio: '侄子.(🎵)', },
      { cn: '侄女', pinyin: 'zhí nǚ', en: 'niece (brother\'s side)', audio: '侄女.(🎵)', },
      { cn: '外甥', pinyin: 'wài shēng', en: 'nephew (sister\'s side)', audio: '外甥.(🎵)', },
      { cn: '外甥女', pinyin: 'wài shēng nǚ', en: 'niece (sister\'s side)', audio: '外甥女.(🎵)', },
      
      // { cn: '叔叔', pinyin: 'shū shu', en: 'Uncle (Dad\'s younger brother)', audio: '叔叔.(🎵)', },
      // { cn: '世代', pinyin: 'shì dài', en: 'generation; generation to generation', audio: '', }, 
      // { cn: '双胞胎', pinyin: 'shuāng bāo tāi', en: 'twin', audio: '', },
      // Step Family
    ],
    'Time': [
      { cn: '时钟', pinyin: 'shí zhōng', en: 'clock', audio: '时钟.(🎵)', }, /* 1 */
      { cn: '闹钟', pinyin: 'nào zhōng', en: 'alarm clock', audio: '闹钟.(🎵)', }, /* 1 */
      { cn: '电子报', pinyin: 'diàn zǐ bào', en: 'digital clock', audio: '电子报.(🎵)', }, /* 1 */
      { cn: '古代', pinyin: 'gǔ dài', en: 'ancient history', audio: '古代.(🎵)', }, /* 1 */
      { cn: '沙钟，沙漏', pinyin: 'shā zhōng, shā lòu', en: 'hourglass', audio: '沙钟，沙漏.(🎵)', }, /* 1 */
      { cn: '怀表', pinyin: 'huái biǎo', en: 'pocket watch', audio: '怀表.(🎵)', }, /* 1 */
      { cn: '日晷', pinyin: 'rì guǐ', en: 'sun dial', audio: '日晷.(🎵)', }, /* 1 */
      { cn: '记事日历', pinyin: 'jì shì rì lì', en: 'schedule', audio: '记事日历.(🎵)', },
      { cn: '休息', pinyin: 'xiū xí', en: 'break', audio: '休息.(🎵)', },
      { cn: '日历', pinyin: 'rì lì', en: 'calendar', audio: '日历.(🎵)', },
      { cn: '世纪', pinyin: 'shì jì', en: 'century', audio: '世纪.(🎵)', },
      // { cn: '日期', pinyin: '', en: 'date', audio: '', },
      // { cn: '结束', pinyin: '', en: 'end', audio: '', },
      // { cn: '中世纪', pinyin: '', en: 'middle ages', audio: '', },
      // { cn: '早晨', pinyin: '', en: 'early morning', audio: '', },
      // { cn: '正点', pinyin: '', en: 'punctiality', audio: '', },
      // { cn: '时间', pinyin: '', en: 'time', audio: '', },
      
      { cn: '日出', pinyin: 'rì chū', en: 'sunrise', audio: '日出.(🎵)', },
      { cn: '夕阳', pinyin: 'xī yáng', en: 'sunset', audio: '夕阳.(🎵)', },
  
      { cn: '历史', pinyin: 'lì shǐ', en: 'history', audio: '历史.(🎵)', },
      { cn: '未来', pinyin: 'wèi lái', en: 'future', audio: '未来.(🎵)', },
      { cn: '现在', pinyin: 'xiàn zài', en: 'now', audio: '现在.(🎵)', }, // Ask what is the difference between 目前 and 现在
      { cn: '过去', pinyin: 'guò qù', en: 'past', audio: '过去.(🎵)', },
  
      // { cn: '早上', pinyin: 'zǎoshang', en: 'morning', audio: '', },
      // { cn: '下午', pinyin: 'xiàwǔ', en: 'afternoon', audio: '', },
      // { cn: '晚上', pinyin: 'wǎnshàng', en: 'evening/night', audio: '', },
      // { cn: '黄昏', pinyin: '', en: 'dusk', audio: '', },
      // { cn: '黎明', pinyin: '', en: 'dawn', audio: '', },
      
      { cn: '前天', pinyin: 'qián tiān', en: 'day before yesterday', audio: '前天.(🎵)', },
      { cn: '昨天', pinyin: 'zuó tiān', en: 'yesterday', audio: '昨天.(🎵)', },
      { cn: '今天', pinyin: 'jīn tiān', en: 'today', audio: '今天.(🎵)', },
      { cn: '明天', pinyin: 'míng tiān', en: 'tomorrow', audio: '明天.(🎵)', },
      { cn: '后天', pinyin: 'hòu tiān', en: 'day after tomorrow', audio: '后天.(🎵)', },
  
      { cn: '季节', pinyin: 'jì jié', en: 'seasons', audio: '季节.(🎵)', },
      { cn: '春天', pinyin: 'chūn tiān', en: 'spring', audio: '春天.(🎵)', },
      { cn: '夏天', pinyin: 'xià tiān', en: 'summer', audio: '夏天.(🎵)', },
      { cn: '秋天', pinyin: 'qiū tiān', en: 'autumn/fall', audio: '秋天.(🎵)', },
      { cn: '冬天', pinyin: 'dōng tiān', en: 'winter', audio: '冬天.(🎵)', },
      
      { cn: '年', pinyin: 'nián', en: 'year', audio: '年.(🎵)', },
      { cn: '月', pinyin: 'yuè', en: 'month', audio: '月.(🎵)', },
      { cn: '天', pinyin: 'tiān', en: 'day', audio: '天.(🎵)', },
      { cn: '小时', pinyin: 'xiǎo shí', en: 'hour', audio: '小时.(🎵)', },
      { cn: '分钟', pinyin: 'fēn zhōng', en: 'minute', audio: '分钟.(🎵)', },
      { cn: '秒', pinyin: 'miǎo', en: 'second', audio: '秒.(🎵)', },
      { cn: '毫秒', pinyin: 'háo miǎo', en: 'millisecond', audio: '毫秒.(🎵)', },
      { cn: '点钟', pinyin: 'diǎn zhōng', en: 'oclock', audio: '点钟.(🎵)', },
  
      { cn: '周末', pinyin: 'zhōu mò', en: 'weekend', audio: '周末.(🎵)', },
      { cn: '星期一', pinyin: 'xīng qí yī', en: 'Monday', audio: '星期一.(🎵)', },
      { cn: '星期二', pinyin: 'xīng qí èr', en: 'Tuesday', audio: '星期二.(🎵)', },
      { cn: '星期三', pinyin: 'xīng qí sān', en: 'Wednesday', audio: '星期三.(🎵)', },
      { cn: '星期四', pinyin: 'xīng qí sì', en: 'Thursday', audio: '星期四.(🎵)', },
      { cn: '星期五', pinyin: 'xīng qí wǔ', en: 'Friday', audio: '星期五.(🎵)', },
      { cn: '星期六', pinyin: 'xīng qí liù', en: 'Saturday', audio: '星期六.(🎵)', },
      { cn: '星期天', pinyin: 'xīng qí tiān', en: 'Sunday', audio: '星期天.(🎵)', },
      
      { cn: '一月', pinyin: 'yī yuè', en: 'January', audio: '一月.(🎵)', },
      { cn: '二月', pinyin: 'èr yuè', en: 'Feburary', audio: '二月.(🎵)', },
      { cn: '三月', pinyin: 'sān yuè', en: 'March', audio: '三月.(🎵)', },
      { cn: '四月', pinyin: 'sì yuè', en: 'April', audio: '四月.(🎵)', },
      { cn: '五月', pinyin: 'wǔ yuè', en: 'May', audio: '五月.(🎵)', },
      { cn: '六月', pinyin: 'liù yuè', en: 'June', audio: '六月.(🎵)', },
      { cn: '七月', pinyin: 'qī yuè', en: 'July', audio: '七月.(🎵)', },
      { cn: '八月', pinyin: 'bā yuè', en: 'August', audio: '八月.(🎵)', },
      { cn: '九月', pinyin: 'jiǔ yuè', en: 'September', audio: '九月.(🎵)', },
      { cn: '十月', pinyin: 'shí yuè', en: 'October', audio: '十月.(🎵)', },
      { cn: '十一月', pinyin: 'shí yī yuè', en: 'November', audio: '十一月.(🎵)', },
      { cn: '十二月', pinyin: 'shí èr yuè', en: 'December', audio: '十二月.(🎵)', },
    ],
    'Color': [
      { cn: '颜色', pinyin: 'yán sè', en: 'color', audio: '颜色.(🎵)', },
      { cn: '白色', pinyin: 'bái sè', en: 'white', audio: '白色.(🎵)', },
      { cn: '黑色', pinyin: 'hēi sè', en: 'black', audio: '黑色.(🎵)', },
      { cn: '粉红色', pinyin: 'fěn hóng sè', en: 'pink', audio: '粉红色.(🎵)', },
      { cn: '红色', pinyin: 'hóng sè', en: 'red', audio: '红色.(🎵)', },
      { cn: '蓝色', pinyin: 'lán sè', en: 'blue', audio: '蓝色.(🎵)', },
      { cn: '绿色', pinyin: 'lǜ sè', en: 'green', audio: '绿色.(🎵)', },
      { cn: '黄色', pinyin: 'huáng sè', en: 'yellow', audio: '黄色.(🎵)', },
      { cn: '紫色', pinyin: 'zǐ sè', en: 'purple', audio: '紫色.(🎵)', },
      { cn: '橙色', pinyin: 'chéng sè', en: 'orange', audio: '橙色.(🎵)', },
      { cn: '棕色', pinyin: 'zōng sè', en: 'brown', audio: '棕色.(🎵)', },
      { cn: '灰色', pinyin: 'huī sè', en: 'gray', audio: '灰色.(🎵)', },
      // { cn: '', pinyin: '', en: 'gold', audio: '', },
      // { cn: '', pinyin: '', en: 'silver', audio: '', },
      // { cn: '彩色', pinyin: 'cǎi sè', en: 'multicolor', audio: '', },
      // { cn: '五颜六色', pinyin: 'wǔ yán liù sè ', en: 'colorful', audio: '', },
      // { cn: '莹', pinyin: 'yíng', en: 'beautiful transparent color??', audio: '', }, Confirm the meaning of this word
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
    
    ],
    'Greetings And Farewells': [
      { cn: '你好', pinyin: 'nǐ hǎo', en: 'hello', audio: '你好.(🎵)', },
      { cn: '您好', pinyin: 'nín hǎo', en: 'hello (polite)', audio: '您好.(🎵)', },
      { cn: '你好吗', pinyin: 'nǐ hǎo ma？', en: 'how are you?', audio: '你好吗.(🎵)', },
      { cn: '您好吗', pinyin: 'nín hǎo ma？', en: 'how are you? (polite)', audio: '您好吗.(🎵)', },
      { cn: '拜拜', pinyin: 'bài bài', en: 'bye bye', audio: '拜拜.(🎵)', },
      { cn: '再会', pinyin: 'zài huì', en: '[we will] hello again', audio: '再会.(🎵)', },
      { cn: '明天见', pinyin: 'míng tiān jiàn', en: 'see you tomorrow', audio: '明天见.(🎵)', },
      { cn: '喂', pinyin: 'wèi', en: 'hey/hi (answering the phone)', audio: '喂.(🎵)', },
      { cn: '再见', pinyin: 'zài jiàn', en: 'goodbye', audio: '再见.(🎵)', },
      { cn: '早上好，你早，早', pinyin: 'zǎo shang hǎo, nǐ zǎo, zǎo', en: 'good morning', audio: '早上好，你早，早.(🎵)', },//zao an
      { cn: '下午好', pinyin: 'xià wǔ hǎo', en: 'good afternoon', audio: '下午好.(🎵)', },
      { cn: '晚上好', pinyin: 'wǎn shàng hǎo', en: 'good evening', audio: '晚上好.(🎵)', },
      { cn: '晚安', pinyin: 'wǎn\'ān', en: 'good night', audio: '晚安.(🎵)', },
      { cn: '你怎么样', pinyin: 'nǐ zěn me yàng?', en: 'how is it going', audio: '你怎么样.(🎵)', },
      { cn: '你的周末怎么样', pinyin: 'nǐ de zhōumò zěnme yàng', en: 'how was your weekend', audio: '你的周末怎么样.(🎵)', },
      { cn: '回头见', pinyin: 'huí tóu jiàn', en: 'see you soon', audio: '回头见.(🎵)', },
      { cn: '下个星期见', pinyin: 'xià gè xīng qí jiàn', en: 'see you next week', audio: '下个星期见.(🎵)', },
      { cn: '改天再聊', pinyin: 'gǎi tiān zài liáo', en: 'talk to you later', audio: '改天再聊.(🎵)', },
      { cn: '慢走', pinyin: 'màn zǒu', en: 'take care', audio: '慢走.(🎵)', },
      
        
    ],
//    'People': [
      // { cn: '学者', pinyin: 'Xuézhě', en: 'scholar', audio: '', },
      // { cn: '学生', pinyin: 'Xuéshēng', en: 'student', audio: '', },
      // { cn: '领导', pinyin: 'Lǐngdǎo', en: 'leader', audio: '', },
      // { cn: '男', pinyin: 'Nán', en: 'male', audio: '', },
      // { cn: '女', pinyin: 'Nǚ', en: 'female', audio: '', },
      // { cn: '男孩', pinyin: 'Nánhái', en: 'boy', audio: '', },
      // { cn: '女孩', pinyin: 'Nǚhái', en: 'girl', audio: '', },
      // { cn: '朋友', pinyin: 'Péngyǒu', en: 'friend', audio: '', },
      // { cn: '人', pinyin: 'Rén', en: 'people/person', audio: '', },
      // { cn: '会员', pinyin: 'Huìyuán', en: 'member', audio: '', },
      // { cn: '房东', pinyin: 'Fángdōng', en: 'landlord', audio: '', },
      // { cn: '队友', pinyin: 'Duìyǒu', en: 'teammate/parter', audio: '', },
      // { cn: '服务员', pinyin: 'Fúwùyuán', en: 'Service Worker', audio: '', },
      // { cn: '参加者', pinyin: 'Cānjiā zhě', en: 'Attendee', audio: '', },
      // { cn: '导师', pinyin: 'Dǎoshī', en: 'tutor', audio: '', },
      // { cn: '对手', pinyin: 'Duìshǒu', en: 'opponent', audio: '', },
      // { cn: '师傅', pinyin: 'Shīfù', en: 'master', audio: '', },
      // { cn: '士兵', pinyin: 'Shìbīng', en: 'soilder', audio: '', },
      // { cn: '英雄', pinyin: 'Yīngxióng', en: 'hero', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },

//    ],
    
    
    'Jobs': [
      { cn: '技术员', pinyin: 'jì shù yuán', en: 'technician', audio: '技术员.(🎵)', },
      { cn: '出纳员', pinyin: 'chū nà yuán', en: 'cashier', audio: '出纳员.(🎵)', },
      { cn: '图书管理员', pinyin: 'tú shū guǎn lǐ yuán', en: 'librarian', audio: '图书管理员.(🎵)', },
      { cn: '接待员', pinyin: 'jiē dài yuán', en: 'receptionist', audio: '接待员.(🎵)', },
      { cn: '秘书', pinyin: 'mì shu', en: 'secretary', audio: '秘书.(🎵)', },
      { cn: '电话推销员', pinyin: 'diàn huà tuī xiāo yuán', en: 'telemarketer', audio: '电话推销员.(🎵)', },
      { cn: '推销员', pinyin: 'tuī xiāo yuán', en: 'saleman', audio: '推销员.(🎵)', },
      { cn: '分析员', pinyin: 'fēn xī yuán', en: 'analyst', audio: '分析员.(🎵)', },
      { cn: '营销人员', pinyin: 'yíng xiāo rén yuán', en: 'marketer', audio: '营销人员.(🎵)', },
      { cn: '工程师', pinyin: 'gōng chéng shī', en: 'engineer', audio: '工程师.(🎵)', },
      { cn: '老师', pinyin: 'lǎo shī', en: 'teacher', audio: '老师.(🎵)', },
      { cn: '培训师', pinyin: 'péi xùn shī', en: 'trainer', audio: '培训师.(🎵)', },
      { cn: '律师', pinyin: 'lǜ shī', en: 'lawyer', audio: '律师.(🎵)', },
      { cn: '治疗师', pinyin: 'zhì liáo shī', en: 'therapist', audio: '治疗师.(🎵)', },
      { cn: '理发师', pinyin: 'lǐ fǎ shī', en: 'barber', audio: '理发师.(🎵)', },
      { cn: '劳动者', pinyin: 'láo dòng zhě', en: 'laborer', audio: '劳动者.(🎵)', },
      { cn: '译者', pinyin: 'yì zhě', en: 'translator', audio: '译者.(🎵)', },
      { cn: '历史学家', pinyin: 'lìshǐ xué jiā', en: 'historian', audio: '历史学家.(🎵)', },
      { cn: '地质学家', pinyin: 'dì zhì xué jia', en: 'geologist', audio: '地质学家.(🎵)', },
      { cn: '艺术家', pinyin: 'yì shù jiā', en: 'artist', audio: '艺术家.(🎵)', },
      { cn: '管家', pinyin: 'guǎn jiā', en: 'housekeeper', audio: '管家.(🎵)', },
      { cn: '经纪人', pinyin: 'jīng jì rén', en: 'broker', audio: '经纪人.(🎵)', },
      { cn: '主人', pinyin: 'zhǔ rén', en: 'host (noun)', audio: '主人.(🎵)', },
      { cn: '撰稿人', pinyin: 'zhuàn gǎo rén', en: 'copywriter', audio: '撰稿人.(🎵)', },
      { cn: '机械', pinyin: 'jī xiè', en: 'mechanic', audio: '机械.(🎵)', },
      { cn: '经理', pinyin: 'jīng lǐ', en: 'manager', audio: '经理.(🎵)', },
      { cn: '人力资源', pinyin: 'rén lì zī yuán', en: 'human resourses', audio: '人力资源.(🎵)', },
      { cn: '护士', pinyin: 'hù shì', en: 'nurse', audio: '护士.(🎵)', },
      { cn: '医生', pinyin: 'yī shēng', en: 'doctor', audio: '医生.(🎵)', },
      { cn: '开发商', pinyin: 'kāi fā shāng', en: 'developer', audio: '开发商.(🎵)', },
      { cn: '教练', pinyin: 'jiào liàn', en: 'coach', audio: '教练.(🎵)', },
      { cn: '算子', pinyin: 'suàn zi', en: 'operator', audio: '算子.(🎵)', },
      { cn: '助理', pinyin: 'zhù lǐ', en: 'assistant', audio: '助理.(🎵)', },
      { cn: '警官', pinyin: 'jǐng guān', en: 'police officer', audio: '警官.(🎵)', },
      { cn: '信使', pinyin: 'xìn shǐ', en: 'mailman', audio: '信使.(🎵)', },
      { cn: '园丁', pinyin: 'yuán dīng', en: 'landscaper', audio: '园丁.(🎵)', },
      { cn: '兽医', pinyin: 'shòu yī', en: 'veterinarian', audio: '兽医.(🎵)', },
      { cn: '代客', pinyin: 'dài kè', en: 'valet', audio: '代客.(🎵)', },
      { cn: '编剧', pinyin: 'biān jù', en: 'screenwriter', audio: '编剧.(🎵)', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },
      // { cn: '', pinyin: '', en: '', audio: '', },

    ],
//    'Vegetables': [
      // { cn: '土豆，马铃薯', pinyin: 'tǔ dòu, mǎ líng shǔ', en: 'potato', audio: '', },
	    // { cn: '胡萝卜', pinyin: 'hú luó bo', en: 'carrot', audio: '', },
	    // { cn: '玉米', pinyin: 'yù mǐ', en: 'corn', audio: '', },
	    // { cn: '大蒜', pinyin: 'dà suàn', en: 'garlic', audio: '', },
	    // { cn: '洋葱', pinyin: 'yáng cōng', en: 'onion', audio: '', },
	    // { cn: '西兰花', pinyin: 'xī lán huā', en: 'broccoli', audio: '', },
	    // { cn: '黄瓜', pinyin: 'huáng guā', en: 'cucumber', audio: '', },
	    // { cn: '夏南瓜', pinyin: 'xià nán guā', en: 'zucchini', audio: '', },
	    // { cn: '牛油果', pinyin: 'niú yóu guǒ.', en: 'avocado', audio: '', },
	    // { cn: '菠菜', pinyin: 'bō cài', en: 'spinach', audio: '', },
	    // { cn: '生菜', pinyin: 'shēng cài', en: 'lettuce', audio: '', },
	    // { cn: '灯笼椒', pinyin: 'dēng lóng jiāo', en: 'bell pepper', audio: '', },
	    // { cn: '豌豆', pinyin: 'wān dòu', en: 'pea', audio: '', },
			// { cn: '菜花', pinyin: 'cài huā', en: 'cauliflower', audio: '', },
			// { cn: '豆子', pinyin: 'dòu zi', en: 'beans', audio: '', },
			// { cn: '橄榄', pinyin: 'gǎn lǎn', en: 'olive', audio: '', },
			// { cn: '球芽甘蓝', pinyin: 'qiú yá gān lán', en: 'brussel sprouts', audio: '', },
			// { cn: '茄子', pinyin: 'qié zi', en: 'eggplant', audio: '', },
			// { cn: '甜菜', pinyin: 'tián cài', en: 'beet, beetroot', audio: '', },
			// { cn: '羽衣甘蓝', pinyin: 'yǔ yī gān lán', en: 'kale', audio: '', },
			// { cn: '朝鲜蓟', pinyin: 'cháo xiǎn jì', en: 'artichoke', audio: '', },
			// { cn: '种子', pinyin: 'zhǒng zǐ', en: 'seed', audio: '', },
			// { cn: '芋头', pinyin: 'yù tou', en: 'taro', audio: '', },
			// { cn: '白饭', pinyin: 'bái fàn', en: 'rice', audio: '', },
	    // { cn: '番茄', pinyin: 'fān qié', en: 'tomato', audio: '', },
	    // { cn: '海藻', pinyin: 'hǎi zǎo', en: 'seaweed', audio: '', },
	    // { cn: '蘑菇', pinyin: 'mó gū', en: 'mushroom', audio: '', },
	    // { cn: '芜菁', pinyin: 'wú jīng', en: 'turnip', audio: '', },
	    // { cn: '芦笋', pinyin: 'lú sǔn', en: 'asparagus', audio: '', },
	    // { cn: '卷心菜', pinyin: 'juǎn xīncài', en: 'cabbage', audio: '', },
	    // { cn: '萝卜', pinyin: 'luó bo', en: 'radish', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
	    // { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },
			// { cn: '', pinyin: '', en: '', audio: '', },

//    ],
//    school: [],
//    animals: [],
//      weather: [
//			  { cn: '', pinyin: '', en: 'barometer', audio: '', },
//			  { cn: '', pinyin: '', en: 'cloud', audio: '', },
//			  { cn: '', pinyin: '', en: 'cold', audio: '', },
//			  { cn: '', pinyin: '', en: 'crescent', audio: '', },
//			  { cn: '', pinyin: '', en: 'darkness', audio: '', },
//			  { cn: '', pinyin: '', en: 'drought', audio: '', },
//			  { cn: '', pinyin: '', en: 'earth', audio: '', },
//			  { cn: '', pinyin: '', en: 'frost', audio: '', },
//			  { cn: '', pinyin: '', en: 'hot', audio: '', },
//			  { cn: '', pinyin: '', en: 'hurricane', audio: '', },
//			  { cn: '', pinyin: '', en: 'icicle', audio: '', },
//			  { cn: '', pinyin: '', en: 'lightning', audio: '', },
//			  { cn: '', pinyin: '', en: 'metor', audio: '', },
//			  { cn: '', pinyin: '', en: 'moon', audio: '', },
//			  { cn: '', pinyin: '', en: 'rainbow', audio: '', },
//			  { cn: '', pinyin: '', en: 'raindrop', audio: '', },
//			  { cn: '', pinyin: '', en: 'snow', audio: '', },
//			  { cn: '', pinyin: '', en: 'snowman', audio: '', },
//			  { cn: '', pinyin: '', en: 'star', audio: '', },
//			  { cn: '', pinyin: '', en: 'storm', audio: '', },
//			  { cn: '', pinyin: '', en: 'sun', audio: '', },
//			  { cn: '', pinyin: '', en: 'sunbeam', audio: '', },
//			  { cn: '', pinyin: '', en: 'sunset', audio: '', },
//			  { cn: '', pinyin: '', en: 'sunrise', audio: '', },
//			  { cn: '', pinyin: '', en: 'thermometer', audio: '', },
//			  { cn: '', pinyin: '', en: 'thunderstorm', audio: '', },
//			  { cn: '', pinyin: '', en: 'twilight', audio: '', },
//			  { cn: '', pinyin: '', en: 'weather', audio: '', },
//			  { cn: '', pinyin: '', en: 'wet conditions', audio: '', },
//			  { cn: '', pinyin: '', en: 'wind', audio: '', },
//			  { cn: '', pinyin: '', en: '', audio: '', },
//			  { cn: '', pinyin: '', en: '', audio: '', },
//			  { cn: '', pinyin: '', en: '', audio: '', },
//			  { cn: '', pinyin: '', en: '', audio: '', },
//			  { cn: '', pinyin: '', en: '', audio: '', },
//			  { cn: '', pinyin: '', en: '', audio: '', },
//			  { cn: '', pinyin: '', en: '', audio: '', },
//			  { cn: '', pinyin: '', en: '', audio: '', },
//			  { cn: '', pinyin: '', en: '', audio: '', },
//      ],
//    sports: [],
//    tools: [],
//    vehicles: [],
//    mathimatics: [
//      { cn: '加', pinyin: 'jiā', en: 'plus', audio: '', },
//      { cn: '添加', pinyin: 'tiān jiā', en: 'add, addition', audio: '', },
//      { cn: '减', pinyin: 'jiǎn', en: 'minus', audio: '', },
//      { cn: '减法', pinyin: 'jiǎn fǎ', en: 'subtraction', audio: '', },
//      { cn: '减去', pinyin: 'jiǎn qù', en: 'subtract', audio: '', },
//      { cn: '', pinyin: '', en: '', audio: '', },
//      { cn: '', pinyin: '', en: '', audio: '', },
//      { cn: '', pinyin: '', en: '', audio: '', },
//      { cn: '', pinyin: '', en: '', audio: '', },
//      { cn: '', pinyin: '', en: '', audio: '', },
//      { cn: '', pinyin: '', en: '', audio: '', },
//      { cn: '', pinyin: '', en: '', audio: '', },
//      { cn: '', pinyin: '', en: '', audio: '', },
//      { cn: '', pinyin: '', en: '', audio: '', },
//      { cn: '', pinyin: '', en: '', audio: '', },
//
//    ],
    'Furniture': [
			{ cn: '家具', pinyin: 'jiā jù', en: 'furniture', audio: '家具.(🎵)', },
			{ cn: '椅子', pinyin: 'yǐ zi', en: 'chair', audio: '椅子.(🎵)', },
			{ cn: '长椅', pinyin: 'cháng yǐ', en: 'bench', audio: '长椅.(🎵)', },
			{ cn: '桌子', pinyin: 'zhuō zi', en: 'table', audio: '桌子.(🎵)', },
			{ cn: '沙发', pinyin: 'shā fā', en: 'sofa', audio: '沙发.(🎵)', },
			{ cn: '床', pinyin: 'chuáng', en: 'bed', audio: '床.(🎵)', },
			{ cn: '书桌', pinyin: 'shū zhuō', en: 'desk', audio: '书桌.(🎵)', },
			{ cn: '床垫', pinyin: 'chuáng diàn', en: 'mattress', audio: '床垫.(🎵)', },
			{ cn: '梳妆台', pinyin: 'shū zhuāng tái', en: 'dresser', audio: '梳妆台.(🎵)', },
			{ cn: '电视架', pinyin: 'diàn shì jià', en: 'TV stand', audio: '电视架.(🎵)', },
			{ cn: '书柜', pinyin: 'shū guì', en: 'bookcase', audio: '书柜.(🎵)', },
			{ cn: '双层床', pinyin: 'shuāng céng chuáng', en: 'bunk bed', audio: '双层床.(🎵)', },
			{ cn: '凳子', pinyin: 'dèng zǐ', en: 'stool', audio: '凳子.(🎵)', },
			{ cn: '榻', pinyin: 'tà', en: 'couch', audio: '榻.(🎵)', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
    ],
//    'Emotions': [
//			{ cn: '', pinyin: '', en: 'feelings', audio: '', },
//			{ cn: '', pinyin: '', en: 'affection', audio: '', },
//      { cn: '', pinyin: '', en: 'anger', audio: '', },
//      { cn: '', pinyin: '', en: 'boredom', audio: '', },
//      { cn: '', pinyin: '', en: 'confidence', audio: '', },
//      { cn: '', pinyin: '', en: 'creativity', audio: '', },
//      { cn: '', pinyin: '', en: 'crisis', audio: '', },
//      { cn: '', pinyin: '', en: 'curiosity', audio: '', },
//      { cn: '', pinyin: '', en: 'defeat', audio: '', },
//      { cn: '', pinyin: '', en: 'depression', audio: '', },
//      { cn: '', pinyin: '', en: 'despair', audio: '', },
//      { cn: '', pinyin: '', en: 'disappointment', audio: '', },
//      { cn: '', pinyin: '', en: 'distrust', audio: '', },
//      { cn: '', pinyin: '', en: 'doubt', audio: '', },
//      { cn: '', pinyin: '', en: 'dream', audio: '', },
//      { cn: '', pinyin: '', en: 'fatigue', audio: '', },
//      { cn: '', pinyin: '', en: 'fear', audio: '', },
//      { cn: '', pinyin: '', en: 'fight', audio: '', },
//      { cn: '', pinyin: '', en: 'friendship', audio: '', },
//      { cn: '', pinyin: '', en: 'fun', audio: '', },
//      { cn: '', pinyin: '', en: 'grief', audio: '', },
//      { cn: '', pinyin: '', en: 'grimace', audio: '', },
//      { cn: '', pinyin: '', en: 'happiness', audio: '', },
//      { cn: '', pinyin: '', en: 'hope', audio: '', },
//      { cn: '', pinyin: '', en: 'hunger', audio: '', },
//      { cn: '', pinyin: '', en: 'interest', audio: '', },
//      { cn: '', pinyin: '', en: 'joy', audio: '', },
//      { cn: '', pinyin: '', en: 'kiss', audio: '', },
//      { cn: '', pinyin: '', en: 'loneliness', audio: '', },
//      { cn: '', pinyin: '', en: 'love', audio: '', },
//      { cn: '', pinyin: '', en: 'melancholy', audio: '', },
//      { cn: '', pinyin: '', en: 'mood', audio: '', },
//      { cn: '', pinyin: '', en: 'optimism', audio: '', },
//      { cn: '', pinyin: '', en: 'panic', audio: '', },
//      { cn: '', pinyin: '', en: 'perplexity', audio: '', },
//      { cn: '', pinyin: '', en: 'rage', audio: '', },
//      { cn: '', pinyin: '', en: 'rejection', audio: '', },
//      { cn: '', pinyin: '', en: 'relationship', audio: '', },
//      { cn: '', pinyin: '', en: 'request', audio: '', },
//      { cn: '', pinyin: '', en: 'scream', audio: '', },
//      { cn: '', pinyin: '', en: 'security', audio: '', },
//      { cn: '', pinyin: '', en: 'shock', audio: '', },
//      { cn: '', pinyin: '', en: 'smile', audio: '', },
//      { cn: '', pinyin: '', en: 'tenderness', audio: '', },
//      { cn: '', pinyin: '', en: 'thought', audio: '', },
//      { cn: '', pinyin: '', en: 'thoughtfulness', audio: '', },
//    ],
//    'Music': [
//			{ cn: '', pinyin: '', en: 'music', audio: '', },
//			{ cn: '', pinyin: '', en: 'accordion', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: 'band', audio: '', },
//			{ cn: '', pinyin: '', en: 'banjo', audio: '', },
//			{ cn: '', pinyin: '', en: 'clarinet', audio: '', },
//			{ cn: '', pinyin: '', en: 'concert', audio: '', },
//			{ cn: '', pinyin: '', en: 'drum', audio: '', },
//			{ cn: '', pinyin: '', en: 'drumset', audio: '', },
//			{ cn: '', pinyin: '', en: 'flute', audio: '', },
//			{ cn: '', pinyin: '', en: 'grand piano', audio: '', },
//			{ cn: '', pinyin: '', en: 'guitar', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: 'electric piano/keyboard', audio: '', },
//			{ cn: '', pinyin: '', en: 'music note', audio: '', },
//			{ cn: '', pinyin: '', en: 'saxophone', audio: '', },
//			{ cn: '', pinyin: '', en: 'singer', audio: '', },
//			{ cn: '', pinyin: '', en: 'string', audio: '', },
//			{ cn: '', pinyin: '', en: 'trumpet', audio: '', },
//			{ cn: '', pinyin: '', en: 'trumpeter', audio: '', },
//			{ cn: '', pinyin: '', en: 'violin', audio: '', },
//			{ cn: '', pinyin: '', en: 'violin case', audio: '', },
//			{ cn: '', pinyin: '', en: 'xylophone', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//    ]
//    'Architecture': [
//			{ cn: '', pinyin: '', en: 'architecture', audio: '', },
//			{ cn: '', pinyin: '', en: 'arena', audio: '', },
//			{ cn: '', pinyin: '', en: 'barn', audio: '', },
//			{ cn: '', pinyin: '', en: 'brick house', audio: '', },
//			{ cn: '', pinyin: '', en: 'bridge', audio: '', },
//			{ cn: '', pinyin: '', en: 'building (noun)', audio: '', },
//			{ cn: '', pinyin: '', en: 'castle', audio: '', },
//			{ cn: '', pinyin: '', en: 'castle', audio: '', },
//			{ cn: '', pinyin: '', en: 'cathedral', audio: '', },
//			{ cn: '', pinyin: '', en: 'column', audio: '', },
//			{ cn: '', pinyin: '', en: 'construction site', audio: '', },
//			{ cn: '', pinyin: '', en: 'dome', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: 'football stadium', audio: '', },
//			{ cn: '', pinyin: '', en: 'fort', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: 'gate', audio: '', },
//			{ cn: '', pinyin: '', en: 'lighthouse', audio: '', },
//			{ cn: '', pinyin: '', en: 'monument', audio: '', },
//			{ cn: '', pinyin: '', en: 'mosque', audio: '', },
//			{ cn: '', pinyin: '', en: 'obelisk', audio: '', },
//			{ cn: '', pinyin: '', en: 'office building', audio: '', },
//			{ cn: '', pinyin: '', en: 'roof', audio: '', },
//			{ cn: '', pinyin: '', en: 'ruin (noun)', audio: '', },
//			{ cn: '', pinyin: '', en: 'scaffold', audio: '', },
//			{ cn: '', pinyin: '', en: 'skyscraper', audio: '', },
//			{ cn: '', pinyin: '', en: 'suspension bridge', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//    ],
    'Common Words & Phrases': [
			{ cn: '你叫什么名字？', pinyin: 'nǐ jiào shén me míng zi?', en: 'What is your name?', audio: '你叫什么名字？.(🎵)', },
			{ cn: '我叫。。。', pinyin: 'Wǒ jiào...', en: 'My name is...', audio: '我叫。。。.(🎵)', },
			{ cn: '你贵姓？', pinyin: 'Ní guì xìng? ', en: 'What is your surname?', audio: '你贵姓？.(🎵)', },
			{ cn: '我姓。。。', pinyin: 'Wǒ xìng... ', en: 'My surname is...', audio: '我姓。。。.(🎵)', },
			{ cn: '你多大？', pinyin: 'Nǐ duō dà?', en: 'How old are you?', audio: '你多大？.(🎵)', },
			{ cn: '你来自哪里？', pinyin: 'Nǐ lái zì nǎ li?', en: 'Where do you come from?', audio: '你来自哪里？.(🎵)', },
			{ cn: '我来自。。。', pinyin: 'Wǒ lái zì...', en: 'I come from...', audio: '我来自。。。.(🎵)', },
			{ cn: '你是哪国人？', pinyin: 'Nǐ shì nǎ guó rén?', en: 'Which country are you from?', audio: '你是哪国人？.(🎵)', },
			{ cn: '我是外国人。', pinyin: 'Wǒ shì wài guó rén.', en: 'I am a foreigner.', audio: '我是外国人。.(🎵)', },
			{ cn: '不好意思。', pinyin: 'Bù hǎo yì si.', en: 'Excuse me/Sorry.', audio: '不好意思。.(🎵)', },
			{ cn: '对不起。', pinyin: 'Duì bu qǐ.', en: 'Sorry [To get attention, for getting past, for mild apologies].', audio: '对不起。.(🎵)', },
			{ cn: '请问。。。？', pinyin: 'Qǐng wèn...? ', en: 'Could I Ask...?', audio: '请问。。。？.(🎵)', },
			{ cn: '麻烦你了。', pinyin: 'Mǎ fan nǐ le.', en: 'Sorry to bother you.', audio: '麻烦你了。.(🎵)', },
			{ cn: '好的！', pinyin: 'Hǎo de!', en: 'Ok!', audio: '好的！.(🎵)', },
			{ cn: '没问题。', pinyin: 'Méi wèn tí.', en: 'No problem.', audio: '没问题。.(🎵)', },
			{ cn: '你听得懂吗？', pinyin: 'Nǐ tīng de dǒng ma? ', en: 'Do you understand?', audio: '你听得懂吗？.(🎵)', },
			{ cn: '我听得懂。', pinyin: ' Wǒ tīng de dǒng.', en: 'I understand.', audio: '我听得懂。.(🎵)', },
			{ cn: '我听不懂。', pinyin: 'Wǒ tīng bu dǒng.', en: 'I do not understand.', audio: '我听不懂。.(🎵)', },
			{ cn: '你会说。。。？', pinyin: 'Nǐ huì shuō...?', en: 'Do you speak...?', audio: '你会说。。。？.(🎵)', },
			{ cn: '我会说。', pinyin: 'Wǒ huì shuō.', en: 'I can speak it. (Yes, I can speak it.)', audio: '我会说。.(🎵)', },
			{ cn: '可以说得慢一点吗？', pinyin: 'Kě yǐ shuō de màn yī diǎn ma?', en: 'Could you speak more slowly?', audio: '可以说得慢一点吗？.(🎵)', },
			{ cn: '。。。什么意思？', pinyin: '...shén me yì si?', en: 'What does... mean?', audio: '。。。什么意思？.(🎵)', },
			{ cn: '。。。怎么说？', pinyin: '...zěn me shuō?', en: 'How do you say...?', audio: '。。。怎么说？.(🎵)', },
			{ cn: '我不知道。', pinyin: 'Wǒ bù zhī dao.', en: 'I do not know.', audio: '我不知道。.(🎵)', },
			{ cn: '不好意思，可以问个路玛？', pinyin: 'Bù hǎo yì si, kě yǐ wèn ge lù ma?', en: 'Excuse me, could I ask for some directions?', audio: '不好意思，可以问个路玛？.(🎵)', },
			{ cn: '到。。。怎么走？', pinyin: 'Dào... zěn me zǒu?', en: 'How do you get to the...?', audio: '到。。。怎么走？.(🎵)', },
			{ cn: '。。。在哪儿？/。。。在哪里？', pinyin: '...zài nǎ r?/...zài nǎ li? ', en: 'Where is the...?', audio: '。。。在哪儿？ 。。。在哪里？.(🎵)', },
			{ cn: '。。。在那儿/。。。在那里', pinyin: '...zài nà r./...zài nà lǐ.', en: 'The... is over there.', audio: '。。。在那儿 。。。在那里.(🎵)', },
			{ cn: '在这儿。/在这里。', pinyin: 'Zài zhè r./Zài zhè lǐ.', en: 'It is here.', audio: '在这儿。在这里。.(🎵)', },
			{ cn: '直走。', pinyin: 'Zhí zǒu.', en: 'Go straight ahead.', audio: '直走。.(🎵)', },
			{ cn: '右转。', pinyin: 'Yòu zhuǎn.', en: 'Turn Right.', audio: '右转。.(🎵)', },
			{ cn: '左转。', pinyin: 'Zuǒ zhuǎn.', en: 'Turn Left.', audio: '左转。.(🎵)', },
			{ cn: '过马路。', pinyin: 'Guò mǎ lù.', en: 'Cross the road.', audio: '过马路。.(🎵)', },
			{ cn: '我要去。。。', pinyin: 'Wǒ yào qù...', en: 'I want to go to...', audio: '我要去。。。.(🎵)', },
			{ cn: '一张到。。。', pinyin: 'Yī zhāng dào...', en: 'One ticket to...', audio: '一张到。。。.(🎵)', },
			{ cn: '两张票。', pinyin: 'Liǎng zhāng piào.', en: 'Two tickets.', audio: '两张票。.(🎵)', },
			{ cn: '单程。', pinyin: 'Dān chéng.', en: 'One way.', audio: '单程。.(🎵)', },
			{ cn: '来回。', pinyin: 'Lái huí.', en: 'Return trip./Round trip.', audio: '来回。.(🎵)', },
			{ cn: '几位？', pinyin: 'Jǐ wèi?', en: 'How many spots? (How many people?)', audio: '几位？.(🎵)', },
			{ cn: '一位。', pinyin: 'Yī wèi.', en: 'One spot. (One person.)', audio: '一位。.(🎵)', },
			{ cn: '两位。', pinyin: 'Liǎng wèi.', en: 'Two spots. (Two people.)', audio: '两位。.(🎵)', },
			{ cn: '我想看一下菜单。', pinyin: 'Wǒ xiǎng kàn yīxià càidān.', en: 'I would like to look at the menu.', audio: '我想看一下菜单。.(🎵)', },
			{ cn: '点菜。', pinyin: 'Diǎn cài.', en: 'Ready to order.', audio: '点菜。.(🎵)', },
			{ cn: '我要。。。', pinyin: 'Wǒ yào...', en: 'I will have...', audio: '我要。。。.(🎵)', },
			{ cn: '买单！', pinyin: 'Mǎi dān!', en: 'The bill, please!', audio: '买单！.(🎵)', },
			{ cn: '这个。', pinyin: 'Zhè ge.', en: 'This one.', audio: '这个。.(🎵)', },
			{ cn: '那个。', pinyin: 'Nà ge.', en: 'That one.', audio: '那个。.(🎵)', },
			{ cn: '我要这个。', pinyin: 'Wǒ yào zhè ge.', en: 'I’ll take this one.', audio: '我要这个。.(🎵)', },
			{ cn: '我喜欢那个。', pinyin: 'Wǒ xǐ huan nà ge.', en: 'I like that one.', audio: '我喜欢那个。.(🎵)', },
			{ cn: '我不喜欢那个。', pinyin: 'Wǒ bù xǐ huan nà ge.', en: 'I do not like that one.', audio: '我不喜欢那个。.(🎵)', },
			{ cn: '多少钱？', pinyin: 'Duō shao qián?', en: 'How much is it?', audio: '多少钱？.(🎵)', },
			{ cn: '太贵了！', pinyin: 'Tài guì le!', en: 'Too expensive!', audio: '太贵了！.(🎵)', },
			{ cn: '便宜一点儿！', pinyin: 'Pián yi yī diǎn r! ', en: 'A bit cheaper!', audio: '便宜一点儿！.(🎵)', },
			{ cn: '可以刷卡吗？', pinyin: 'Kě yǐ shuā kǎ ma?', en: 'Can I use a card?', audio: '可以刷卡吗？.(🎵)', },
			{ cn: '不要了！', pinyin: 'Bù yào le!', en: 'I do not want it!', audio: '不要了！.(🎵)', },
			{ cn: '我看一下。', pinyin: 'Wǒ kàn yī xià.', en: 'I am just looking.', audio: '我看一下。.(🎵)', },
			{ cn: '可以帮个忙吗？', pinyin: 'Kě yǐ bāng ge máng ma?', en: 'Can you help me?', audio: '可以帮个忙吗？.(🎵)', },
			{ cn: '我迷路了。', pinyin: 'Wǒ mí lù le.', en: 'I am lost.', audio: '我迷路了。.(🎵)', },
			{ cn: '我的钱包丢了。', pinyin: 'Wǒ de qián bāo diū le.', en: 'My wallet is missing.', audio: '我的钱包丢了。.(🎵)', },
			{ cn: '我要去医院。', pinyin: 'Wǒ yào qù yī yuàn.', en: 'I need to go to the hospital.', audio: '我要去医院。.(🎵)', },
			{ cn: '我生病了。', pinyin: 'Wǒ shēng bìng le.', en: 'I am sick.', audio: '我生病了。.(🎵)', },
			{ cn: '我受伤了。', pinyin: 'Wǒ shòu shāng le.', en: 'I am hurt/injured.', audio: '我受伤了。.(🎵)', },
			{ cn: '这里疼。', pinyin: 'Zhè lǐ téng.', en: 'It hurts here.', audio: '这里疼。.(🎵)', },
			{ cn: '恭喜恭喜！', pinyin: 'Gōng xǐ gōng xǐ!', en: 'Congratulations!', audio: '恭喜恭喜！.(🎵)', },
			{ cn: '生日快乐！', pinyin: 'Shēng ri kuài lè!', en: 'Happy Birthday!', audio: '生日快乐！.(🎵)', },
			{ cn: '干杯！', pinyin: 'Gān bēi!', en: 'Cheers!', audio: '干杯！.(🎵)', },
			{ cn: '新年快乐！', pinyin: 'Xīn nián kuài lè!', en: 'Happy New Year!', audio: '新年快乐！.(🎵)', },
			{ cn: '恭喜发财！', pinyin: 'Gōng xǐ fā cái!', en: 'May you be prosperous!', audio: '恭喜发财！.(🎵)', },
			{ cn: '祝你好运！', pinyin: 'Zhù nǐ hǎo yùn!', en: 'Good Luck!', audio: '祝你好运！.(🎵)', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', }.
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', }.
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', }.
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', }.
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', }.
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', }.
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
      ],
//    electric: [],
//    plumbing: [],
//    clothes: [],
//    materials: [],
//    electronics: [],
//    verbs: [],
//    adjectives: [],
//    phrases: [],
//    office: [],
//    government: [],
//    geography: [],
//    medical: [],
//    places: [
//			{ cn: '', pinyin: '', en: 'Airport', audio: '', },
//			{ cn: '', pinyin: '', en: 'Train station', audio: '', },
//			{ cn: '', pinyin: '', en: 'Metro/subway/underground station', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//			{ cn: '', pinyin: '', en: '', audio: '', },
//
//    ],
//      'Countries': [
//        // Country Refernces
//        // https://www.worldometers.info/geography/how-many-countries-are-there-in-the-world/
//			  { cn: '尼日利亚', pinyin: 'Nírìlìyǎ', en: 'Nigeria', flag: '🇳🇬', audio: '', },
//			  { cn: '埃塞俄比亚', pinyin: 'Āisāi\'ébǐyǎ', en: 'Ethipoia', flag: '🇪🇹', audio: '', },
//			  { cn: '埃及', pinyin: 'Āijí', en: 'Egypt', flag: '🇪🇬', audio: '', },
//			  { cn: '刚果民主共和国', pinyin: 'Gāngguǒ mínzhǔ gònghéguó', en: 'Democratic Republic of the Congo', flag: '🇨🇩', audio: '', },
//			  { cn: '坦桑尼亚', pinyin: 'Tǎnsāngníyǎ', en: 'Tanzania', flag: '🇹🇿', audio: '', },
//			  { cn: '南非', pinyin: 'Nánfēi', en: 'South Africa', flag: '🇿🇦', audio: '', },
//			  { cn: '肯尼亚', pinyin: 'Kěnníyǎ', en: 'Kenya', flag: '🇰🇪', audio: '', },
//			  { cn: '乌干达', pinyin: 'Wūgāndá', en: 'Uganda', flag: '🇺🇬', audio: '', },
//			  { cn: '阿尔及利亚', pinyin: 'Ā\'ěrjílìyǎ', en: 'Algeria', flag: '🇩🇿', audio: '', },
//			  { cn: '苏丹', pinyin: 'Sūdān', en: 'Sudan', flag: '🇸🇩', audio: '', },
//			  { cn: '摩洛哥', pinyin: 'Móluògē', en: 'Morocco', flag: '🇲🇦', audio: '', },
//			  { cn: '安哥拉', pinyin: 'Āngēlā', en: 'Angola', flag: '🇦🇴', audio: '', },
//			  { cn: '莫桑比克', pinyin: 'Mòsāngbǐkè', en: 'Mozambique', flag: '🇲🇿', audio: '', },
//			  { cn: '加纳', pinyin: 'Jiānà', en: 'Ghana', flag: '🇬🇭', audio: '', },
//			  { cn: '马达加斯加', pinyin: 'Mǎdájiāsījiā', en: 'Madagascar', flag: '🇲🇬', audio: '', },
//			  { cn: '喀麦隆', pinyin: 'Kāmàilóng', en: 'Cameroon', flag: '🇨🇲', audio: '', },
//			  { cn: '科特迪瓦', pinyin: 'Kētèdíwǎ', en: 'Côte d\'Ivoire', flag: '🇨🇮', audio: '', },
//			  { cn: '尼日尔', pinyin: 'Nírì\'ěr', en: 'Niger', flag: '🇳🇪', audio: '', },
//			  { cn: '布基纳法索', pinyin: 'Bù jī nà fǎ suǒ', en: 'Burkina Faso', flag: '🇧🇫', audio: '', },
//			  { cn: '马里', pinyin: 'Mali', en: 'Mali', flag: '🇲🇱', audio: '', },
//			  { cn: '马拉维', pinyin: 'Mǎ lā wéi', en: 'Malawi', flag: '🇲🇼', audio: '', },
//			  { cn: '赞比亚', pinyin: 'Zànbǐyǎ', en: 'Zambia', flag: '🇿🇲', audio: '', },
//			  { cn: '塞内加尔', pinyin: 'Sàinèijiā\'ěr', en: 'Senegal', flag: '🇸🇳', audio: '', },
//			  { cn: '乍得', pinyin: 'Zhàdé', en: 'Chad', flag: '🇹🇩', audio: '', },
//			  { cn: '索马里', pinyin: 'Suǒmǎlǐ', en: 'Somalia', flag: '🇸🇴', audio: '', },
//			  { cn: '津巴布韦', pinyin: 'Jīnbābùwéi', en: 'Zimbabwe', flag: '🇿🇼', audio: '', },
//			  { cn: '几内亚', pinyin: 'Jǐnèiyǎ', en: 'Guninea', flag: '🇬🇳', audio: '', },
//			  { cn: '卢旺达', pinyin: 'Lúwàngdá', en: 'Rwanda', flag: '🇷🇼', audio: '', },
//			  { cn: '贝宁', pinyin: 'Bèi níng', en: 'Benin', flag: '🇧🇯', audio: '', },
//			  { cn: '布隆迪', pinyin: 'Bùlóngdí', en: 'Burundi', flag: '🇧🇮', audio: '', },
//			  { cn: '突尼斯', pinyin: 'Túnísī', en: 'Tunisia', flag: '🇹🇳', audio: '', },
//			  { cn: '南苏丹', pinyin: 'Nán sūdān', en: 'South Sudan', flag: '🇸🇸', audio: '', },
//			  { cn: '多哥', pinyin: 'Duō gē', en: 'Togo', flag: '🇹🇬', audio: '', },
//			  { cn: '塞拉利昂', pinyin: 'Sèlālì\'áng', en: 'Sierra Leone', flag: '🇸🇱', audio: '', },
//			  { cn: '利比亚', pinyin: 'Lìbǐyǎ', en: 'Libya', flag: '🇱🇾', audio: '', },
//			  { cn: '刚果', pinyin: 'Gāngguǒ', en: 'Republic of the Congo', flag: '🇨🇬', audio: '', },
//			  { cn: '利比里亚', pinyin: 'Lìbǐlǐyǎ', en: 'Liberia', flag: '🇱🇷', audio: '', },
//			  { cn: '中非共和国', pinyin: 'Zhōng fēi gònghéguó', en: 'Central African Republic', flag: '🇨🇫', audio: '', },
//			  { cn: '毛里塔尼亚', pinyin: 'Máolǐtǎníyǎ', en: 'Mauritania', flag: '🇲🇷', audio: '', },
//			  { cn: '厄立特里亚', pinyin: 'Èlìtèlǐyǎ', en: 'Eritrea', flag: '🇪🇷', audio: '', },
//			  { cn: '纳米比亚', pinyin: 'Nàmǐbǐyǎ', en: 'Namibia', flag: '🇳🇦', audio: '', },
//			  { cn: '冈比亚', pinyin: 'Gāngbǐyǎ', en: 'Gambia', flag: '🇬🇲', audio: '', },
//			  { cn: '博茨瓦纳', pinyin: 'Bócíwǎnà', en: 'Botswana', flag: '🇧🇼', audio: '', },
//			  { cn: '加蓬', pinyin: 'Jiāpéng', en: 'Gabon', flag: '🇬🇦', audio: '', },
//			  { cn: '莱索托', pinyin: 'Láisuǒtuō', en: 'Lesotho', flag: '🇱🇸', audio: '', },
//			  { cn: '几内亚比绍', pinyin: 'Jǐnèiyǎ bǐ shào', en: 'Guinea-Bissau', flag: '🇬🇼', audio: '', },
//			  { cn: '赤道几内亚', pinyin: 'Chìdào jǐnèiyǎ', en: 'Equatorial Guinea', flag: '🇬🇶', audio: '', },
//			  { cn: '毛里求斯', pinyin: 'Máolǐqiúsī', en: 'Mauritius', flag: '🇲🇺', audio: '', },
//			  { cn: '埃斯瓦蒂尼', pinyin: 'Āi sī wǎ dì ní', en: 'Eswatini', flag: '🇸🇿', audio: '', },
//			  { cn: '吉布提', pinyin: 'Jíbùtí', en: 'Djibouti', flag: '🇩🇯', audio: '', },
//			  { cn: '科摩罗', pinyin: 'Kē mó luó', en: 'Comoros', flag: '🇰🇲', audio: '', },
//			  { cn: '佛得角', pinyin: 'Fú dé jiǎo', en: 'Cabo Verde', flag: '🇨🇻', audio: '', },
//			  { cn: '圣多美和普林西比', pinyin: 'Shèng duō měihé pǔ lín xī bǐ', en: 'Sao Tome & Principe', flag: '🇸🇹', audio: '', },
//			  { cn: '塞舌尔', pinyin: 'Sāi shé ěr', en: 'Seychelles', flag: '🇸🇨', audio: '', },
//			  { cn: '中国', pinyin: 'Zhōngguó', en: 'China', flag: '🇨🇳', audio: '', },
//			  { cn: '印度', pinyin: 'Yìndù', en: 'India', flag: '🇮🇳', audio: '', },
//			  { cn: '印度尼西亚', pinyin: 'Yìndùníxīyà', en: 'Indonesia', flag: '🇮🇩', audio: '', },
//			  { cn: '巴基斯坦', pinyin: 'Bājīsītǎn', en: 'Pakistan', flag: '🇵🇰', audio: '', },
//			  { cn: '孟加拉国', pinyin: 'Mèngjiālā guó', en: 'Bangladesh', flag: '🇧🇩', audio: '', },
//			  { cn: '日本', pinyin: 'Rìběn', en: 'Japan', flag: '🇯🇵', audio: '', },
//			  { cn: '菲律宾', pinyin: 'Fēilǜbīn', en: 'Philippines', flag: '🇵🇭', audio: '', },
//			  { cn: '越南', pinyin: 'Yuènán', en: 'Vietnam', flag: '🇻🇳', audio: '', },
//			  { cn: '火鸡', pinyin: 'Huǒ jī', en: 'Turkey', flag: '🇹🇷', audio: '', },
//			  { cn: '伊朗', pinyin: 'Yīlǎng', en: 'Iran', flag: '🇮🇷', audio: '', },
//			  { cn: '泰国', pinyin: 'Tàiguó', en: 'Thailand', flag: '🇹🇭', audio: '', },
//			  { cn: '缅甸', pinyin: 'Miǎndiàn', en: 'Myanmar', flag: '🇲🇲', audio: '', },
//			  { cn: '韩国', pinyin: 'Hánguó', en: 'South Korea', flag: '🇰🇷', audio: '', },
//			  { cn: '伊拉克', pinyin: 'Yīlākè', en: 'Iraq', flag: '🇮🇶', audio: '', },
//			  { cn: '阿富汗', pinyin: 'Āfùhàn', en: 'Afghanistan', flag: '🇦🇫', audio: '', },
//			  { cn: '马来西亚', pinyin: 'Mǎláixīyà', en: 'Malaysia', flag: '🇲🇾', audio: '', },
//			  { cn: '也门', pinyin: 'Yěmén', en: 'Yemen', flag: '🇾🇪', audio: '', },
//			  { cn: '尼泊尔', pinyin: 'Níbó'ěr', en: 'Nepal', flag: '🇳🇵', audio: '', },
//			  { cn: '北朝鲜', pinyin: 'Běi cháoxiǎn', en: 'North Korea', flag: '🇰🇵', audio: '', },
//			  { cn: '斯里兰卡', pinyin: 'Sri Lanka', en: 'Sri Lanka', flag: '🇱🇰', audio: '', },
//			  { cn: '哈萨克斯坦', pinyin: 'Hāsàkè sītǎn', en: 'Kazakhstan', flag: '🇰🇿', audio: '', },
//			  { cn: '叙利亚', pinyin: 'Xùlìyǎ', en: 'Syria', flag: '🇸🇾', audio: '', },
//			  { cn: '柬埔寨', pinyin: 'Jiǎnpǔzhài', en: 'Cambodia', flag: '🇰🇭', audio: '', },
//			  { cn: '约旦', pinyin: 'Yuēdàn', en: 'Jordan', flag: '🇯🇴', audio: '', },
//			  { cn: '阿塞拜疆', pinyin: 'Āsèbàijiāng', en: 'Azerbaijan', flag: '🇦🇿', audio: '', },
//			  { cn: '阿拉伯联合酋长国', pinyin: 'Ālābó liánhé qiúzhǎngguó', en: 'United Arab Emirates', flag: '🇦🇪', audio: '', },
//			  { cn: '塔吉克斯坦', pinyin: 'Tǎjíkè sītǎn', en: 'Tajikistan', flag: '🇹🇯', audio: '', },
//			  { cn: '以色列', pinyin: 'Yǐsèliè', en: 'Israel', flag: '🇮🇱', audio: '', },
//			  { cn: '老挝', pinyin: 'Lǎowō', en: 'Laos', flag: '🇱🇦', audio: '', },
//			  { cn: '黎巴嫩', pinyin: 'Líbānèn', en: 'Lebanon', flag: '🇱🇧', audio: '', },
//			  { cn: '吉尔吉斯斯坦', pinyin: 'Jí\'ěrjísī sītǎn', en: 'Kyrgyzstan', flag: '🇰🇬', audio: '', },
//			  { cn: '土库曼斯坦', pinyin: 'Tǔkùmàn sītǎn', en: 'Turkmenistan', flag: '🇹🇲', audio: '', },
//			  { cn: '新加坡', pinyin: 'Xīnjiāpō', en: 'Singapore', flag: '🇸🇬', audio: '', },
//			  { cn: '阿曼', pinyin: 'Āmàn', en: 'Oman', flag: '🇴🇲', audio: '', },
//			  { cn: '巴勒斯坦国', pinyin: 'Bālèsītǎn guó', en: 'State of Palestine', flag: '🇵🇸', audio: '', },
//			  { cn: '科威特', pinyin: 'Kēwēitè', en: 'Kuwait', flag: '🇰🇼', audio: '', },
//			  { cn: '乔治亚州', pinyin: 'Qiáozhìyà zhōu', en: 'Georgia', flag: '🇬🇪', audio: '', },
//			  { cn: '蒙古', pinyin: 'Ménggǔ', en: 'Mongolia', flag: '🇲🇳', audio: '', },
//			  { cn: '亚美尼亚', pinyin: 'Yàměiníyǎ', en: 'Armenia', flag: '🇦🇲', audio: '', },
//			  { cn: '卡塔尔', pinyin: 'Kǎtǎ\'ěr', en: 'Qatar', flag: '🇶🇦', audio: '', },
//			  { cn: '巴林', pinyin: 'Bālín', en: 'Bahrain', flag: '🇧🇭', audio: '', },
//			  { cn: '东帝汶', pinyin: 'Dōngdìwèn', en: 'Timor-Leste', flag: '🇹🇱', audio: '', },
//			  { cn: '塞浦路斯', pinyin: 'Sāipǔlùsī', en: 'Cyprus', flag: '🇨🇾', audio: '', },
//			  { cn: '不丹', pinyin: 'Bù dān', en: 'Bhutan', flag: '🇧🇹', audio: '', },
//			  { cn: '马尔代夫', pinyin: 'Mǎ\'ěrdàifū', en: 'Maldives', flag: '🇲🇻', audio: '', },
//			  { cn: '文莱', pinyin: 'Wén lái', en: 'Brunei', flag: '🇧🇳', audio: '', },
//			  { cn: '俄罗斯', pinyin: 'Èluósī', en: 'Russia', flag: '🇷🇺', audio: '', },
//			  { cn: '德国', pinyin: 'Déguó', en: 'Germany', flag: '🇩🇪', audio: '', },
//			  { cn: '英国', pinyin: 'Yīngguó', en: 'United Kingdom', flag: '🇬🇧', audio: '', },
//			  { cn: '法国', pinyin: 'Fàguó', en: 'France', flag: '🇫🇷', audio: '', },
//			  { cn: '意大利', pinyin: 'Yìdàlì', en: 'Italy', flag: '🇮🇹', audio: '', },
//			  { cn: '西班牙', pinyin: 'Xībānyá', en: 'Spain', flag: '🇪🇸', audio: '', },
//			  { cn: '乌克兰', pinyin: 'Wūkèlán', en: 'Ukraine', flag: '🇺🇦', audio: '', },
//			  { cn: '波兰', pinyin: 'Bōlán', en: 'Poland', flag: '🇵🇱', audio: '', },
//			  { cn: '罗马尼亚', pinyin: 'Luómǎníyǎ', en: 'Romania', flag: '🇷🇴', audio: '', },
//			  { cn: '荷兰', pinyin: 'Hélán', en: 'Netherlands', flag: '🇳🇱', audio: '', },
//			  { cn: '比利时', pinyin: 'Bǐlìshí', en: 'Belgium', flag: '🇧🇪', audio: '', },
//			  { cn: '捷克共和国（捷克）', pinyin: 'Jiékè gònghéguó (jiékè)', en: 'Czech Republic (Czechia)', flag: '🇨🇿', audio: '', },
//			  { cn: '希腊', pinyin: 'Xīlà', en: 'Greece', flag: '🇬🇷', audio: '', },
//			  { cn: '葡萄牙', pinyin: 'Pútáoyá', en: 'Portugal', flag: '🇵🇹', audio: '', },
//			  { cn: '瑞典', pinyin: 'Ruìdiǎn', en: 'Sweden', flag: '🇸🇪', audio: '', },
//			  { cn: '匈牙利', pinyin: 'Xiōngyálì', en: 'Hungary', flag: '🇭🇺', audio: '', },
//			  { cn: '白俄罗斯', pinyin: 'Bái\'èluósī', en: 'Belarus', flag: '🇧🇾', audio: '', },
//			  { cn: '奥地利', pinyin: 'Àodìlì', en: 'Austria', flag: '🇦🇹', audio: '', },
//			  { cn: '塞尔维亚', pinyin: 'Sài\'ěrwéiyǎ', en: 'Serbia', flag: '🇷🇸', audio: '', },
//			  { cn: '瑞士', pinyin: 'Ruìshì', en: 'Switzerland', flag: '🇨🇭', audio: '', },
//			  { cn: '保加利亚', pinyin: 'Bǎojiālìyǎ', en: 'Bulgaria', flag: '🇧🇬', audio: '', },
//			  { cn: '丹麦', pinyin: 'Dānmài', en: 'Denmark', flag: '🇩🇰', audio: '', },
//			  { cn: '芬兰', pinyin: 'Fēnlán', en: 'Finland', flag: '🇫🇮', audio: '', },
//			  { cn: '斯洛伐克', pinyin: 'Sīluòfákè', en: 'Slovakia', flag: '🇸🇰', audio: '', },
//			  { cn: '挪威', pinyin: 'Nuówēi', en: 'Norway', flag: '🇳🇴', audio: '', },
//			  { cn: '爱尔兰', pinyin: 'Ài\'ěrlán', en: 'Ireland', flag: '🇮🇪', audio: '', },
//			  { cn: '克罗地亚', pinyin: 'Kèluódìyà', en: 'Croatia', flag: '🇭🇷', audio: '', },
//			  { cn: '摩尔多瓦', pinyin: 'Mó\'ěrduōwǎ', en: 'Moldova', flag: '🇲🇩', audio: '', },
//			  { cn: '波斯尼亚和黑塞哥维那', pinyin: 'Bōsīníyǎ hé hēisāigēwéinà', en: 'Bosnia and Herzegovina', flag: '🇧🇦', audio: '', },
//			  { cn: '阿尔巴尼亚', pinyin: 'Ā\'ěrbāníyǎ', en: 'Albania', flag: '🇦🇱', audio: '', },
//			  { cn: '立陶宛', pinyin: 'Lìtáowǎn', en: 'Lithuania', flag: '🇱🇹', audio: '', },
//			  { cn: '北马其顿', pinyin: 'Běi mǎqídùn', en: 'North Macedonia', flag: '🇲🇰', audio: '', },
//			  { cn: '斯洛文尼亚', pinyin: 'Sīluòwénníyǎ', en: 'Slovenia', flag: '🇸🇮', audio: '', },
//			  { cn: '拉脱维亚', pinyin: 'Lātuōwéiyǎ', en: 'Latvia', flag: '🇱🇻', audio: '', },
//			  { cn: '爱沙尼亚', pinyin: 'Àishāníyǎ', en: 'Estonia', flag: '🇪🇪', audio: '', },
//			  { cn: '黑山', pinyin: 'Hēishān', en: 'Montenegro', flag: '🇲🇪', audio: '', },
//			  { cn: '卢森堡', pinyin: 'Lúsēnbǎo', en: 'Luxembourg', flag: '🇱🇺', audio: '', },
//			  { cn: '马耳他', pinyin: 'Mǎ\'ěrtā', en: 'Malta', flag: '🇲🇹', audio: '', },
//			  { cn: '冰岛', pinyin: 'Bīngdǎo', en: 'Iceland', flag: '🇮🇸', audio: '', },
//			  { cn: '安道尔', pinyin: 'Āndào ěr', en: 'Andorra', flag: '🇦🇩', audio: '', },
//			  { cn: '摩纳哥', pinyin: 'Mónàgē', en: 'Monaco', flag: '🇲🇨', audio: '', },
//			  { cn: '列支敦士登', pinyin: 'Lièzhīdūnshìdēng', en: 'Liechtenstein', flag: '🇱🇮', audio: '', },
//			  { cn: '圣马力诺', pinyin: 'Shèngmǎlìnuò', en: 'San Marino', flag: '🇸🇲', audio: '', },
//			  { cn: '教廷', pinyin: 'Jiàotíng', en: 'Holy See', flag: '🇻🇦', audio: '', },
//			  { cn: '巴西', pinyin: 'Bāxī', en: 'Brazil', flag: '🇧🇷', audio: '', },
//			  { cn: '墨西哥', pinyin: 'Mòxīgē', en: 'Mexico', flag: '🇲🇽', audio: '', },
//			  { cn: '哥伦比亚', pinyin: 'Gēlúnbǐyǎ', en: 'Colombia', flag: '🇨🇴', audio: '', },
//			  { cn: '阿根廷', pinyin: 'Āgēntíng', en: 'Argentina', flag: '🇦🇷', audio: '', },
//			  { cn: '秘鲁', pinyin: 'Bìlǔ', en: 'Peru', flag: '🇵🇪', audio: '', },
//			  { cn: '委内瑞拉', pinyin: 'Wěinèiruìlā', en: 'Venezuela', flag: '🇻🇪', audio: '', },
//			  { cn: '智利', pinyin: 'Zhìlì', en: 'Chile', flag: '🇨🇱', audio: '', },
//			  { cn: '危地马拉', pinyin: 'Wēidìmǎlā', en: 'Guatemala', flag: '🇬🇹', audio: '', },
//			  { cn: '厄瓜多尔', pinyin: 'Èguāduō\'ěr', en: 'Ecuador', flag: '🇪🇨', audio: '', },
//			  { cn: '玻利维亚', pinyin: 'Bōlìwéiyǎ', en: 'Bolivia', flag: '🇧🇴', audio: '', },
//			  { cn: '海地', pinyin: 'Hǎidì', en: 'Haiti', flag: '🇭🇹', audio: '', },
//			  { cn: '古巴', pinyin: 'Gǔbā', en: 'Cuba', flag: '🇨🇺', audio: '', },
//			  { cn: '多明尼加共和国', pinyin: 'Duō míng ní jiā gònghéguó', en: 'Dominican Republic', flag: '🇩🇴', audio: '', },
//			  { cn: '洪都拉斯', pinyin: 'Hóngdūlāsī', en: 'Honduras', flag: '🇭🇳', audio: '', },
//			  { cn: '巴拉圭', pinyin: 'Bālāguī', en: 'Paraguay', flag: '🇵🇾', audio: '', },
//			  { cn: '尼加拉瓜', pinyin: 'Níjiālāguā', en: 'Nicaragua', flag: '🇳🇮', audio: '', },
//			  { cn: '萨尔瓦多', pinyin: 'Sà\'ěrwǎduō', en: 'El Salvador', flag: '🇸🇻', audio: '', },
//			  { cn: '哥斯达黎加', pinyin: 'Gēsīdálíjiā', en: 'Costa Rica', flag: '🇨🇷', audio: '', },
//			  { cn: '巴拿马', pinyin: 'Bānámǎ', en: 'Panama', flag: '🇵🇦', audio: '', },
//			  { cn: '乌拉圭', pinyin: 'Wūlāguī', en: 'Uruguay', flag: '🇺🇾', audio: '', },
//			  { cn: '牙买加', pinyin: 'Yámǎijiā', en: 'Jamaica', flag: '🇯🇲', audio: '', },
//			  { cn: '特立尼达和多巴哥', pinyin: 'Tè lì ní dá hé duō bā gē', en: 'Trinidad and Tobago', flag: '🇹🇹', audio: '', },
//			  { cn: '圭亚那', pinyin: 'Guīyǎnà', en: 'Guyana', flag: '🇬🇾', audio: '', },
//			  { cn: '苏里南', pinyin: 'Sūlǐnán', en: 'Suriname', flag: '🇸🇷', audio: '', },
//			  { cn: '伯利兹', pinyin: 'Bó lìzī', en: 'Belize', flag: '🇧🇿', audio: '', },
//			  { cn: '巴哈马', pinyin: 'Bāhāmǎ', en: 'Bahamas', flag: '🇧🇸', audio: '', },
//			  { cn: '巴巴多斯', pinyin: 'Bābāduōsī', en: 'Barbados', flag: '🇧🇧', audio: '', },
//			  { cn: '圣卢西亚', pinyin: 'Shèng lú xīyǎ', en: 'Saint Lucia', flag: '🇱🇨', audio: '', },
//			  { cn: '格林纳达', pinyin: 'Gélínnàdá', en: 'Grenada', flag: '🇬🇩', audio: '', },
//			  { cn: '圣文森特和格林纳丁斯', pinyin: 'Shèngwénsēntè hé gélín nà dīng sī', en: 'St. Vincent & Grenadines', flag: '🇻🇨', audio: '', },
//			  { cn: '安提瓜和巴布达', pinyin: 'Ān tí guā hé bā bù dá', en: 'Antigua and Barbuda', flag: '🇦🇬', audio: '', },
//
//			  { cn: '多米尼加 {多米尼克国}', pinyin: 'Duōmǐníjiā {Duōmǐ níkè guó}', en: 'Dominica {The Commonwealth of Dominica}', flag: '🇩🇲', audio: '', },
//			  { cn: '澳大利亚联邦', pinyin: 'Àodàlìyǎ liánbāng', en: 'Commonwealth of Australia', flag: '🇦🇺', audio: '', },
//			  { cn: '巴布亚新几内亚独立国', pinyin: 'Bābùyǎ xīn jǐnèiyǎ dúlì guó', en: 'The Independent State of Papua New Guinea', flag: '🇵🇬', audio: '', },
//			  { cn: '新西兰', pinyin: 'Xīnxīlán', en: 'New Zealand', flag: '🇳🇿', audio: '', },
//			  { cn: '斐济共和国', pinyin: 'Fěijì gònghéguó', en: 'The Republic of Fiji', flag: '🇫🇯', audio: '', },
//			  { cn: '所罗门群岛', pinyin: 'Suǒluómén qúndǎo', en: 'Solomon Islands', flag: '🇸🇧', audio: '', },
//			  { cn: '密克罗尼西亚联邦', pinyin: 'Mì kè luó ní xīyǎ liánbāng', en: 'Federated States of Micronesia', flag: '🇫🇲', audio: '', },
//			  { cn: '瓦努阿圖共和國', pinyin: 'Wǎnǔ\'ātú', en: 'Republic of Vanuatu', flag: '🇻🇺', audio: '', },
//			  { cn: '萨摩亚', pinyin: 'Sàmó yǎ', en: 'Samoa', flag: '🇼🇸', audio: '', },
//			  { cn: '基里巴斯', pinyin: 'Jīlǐbāsī', en: 'Kiribati', flag: '🇰🇮', audio: '', },
//			  { cn: '汤加', pinyin: 'Tāngjiā', en: 'Tonga', flag: '🇹🇴', audio: '', },
//			  { cn: '马绍尔群岛共和国', pinyin: 'Mǎshào\'ěr qúndǎo gònghéguó', en: 'Republic of the Marshall Islands', flag: '🇲🇭', audio: '', },
//			  { cn: '帕劳', pinyin: 'Pà láo', en: 'Palau', flag: '🇵🇼', audio: '', },
//			  { cn: '图瓦卢', pinyin: 'Tú wǎ lú', en: 'Tuvalu', flag: '🇹🇻', audio: '', },
//			  { cn: '瑙鲁', pinyin: 'Nǎo lǔ', en: 'Nauru', flag: '🇳🇷', audio: '', },
//			  { cn: '美国', pinyin: 'Měiguó', en: 'United States', flag: '🇺🇸', audio: '', },
//			  { cn: '加拿大', pinyin: 'Jiānádà', en: 'Canada', flag: '🇨🇦', audio: '', },
//      ],
      
}

window['Chinese'] = window['Chinese']
  .map(a => 
    a[1].map(a => 
      a.map(a => 
        a[0] === 'audio' ? a[1] = 'audio/chinese/' + a[1] : a[1]
      )
    )
  )


// Sound Test
//answers
//  .map(a => 
//    a[1].map((a,b) => {
//      const button = $(`<button>${a.audio}</button>`)
//      button.addEventListener('click', () => {
//        new Audio(`./chinese/${a.audio.replace('.(🎵)', '.mp3')}`).play()
//      })
//      $('body').appendChild(button)
//    })
//  )
//  .values()
//  .join('')
//  .replace(/,/g, '')

// () = More Appropriate Translation of the given direct translation
// [] = Scenario in or context of which the word is used 
// {} = Other
// || = Alternatives
// ** = Quick Differentiate
// May require images to bridge the indirect translations of vegetables
// INDICATE MALE AND FEMALE AND FORMAL AND POLITE
// /* 1 */ Thanks to Selene from Hellotalk app for helping out with some of the translations
